class Movie:
    def __init__(self, title, runtime, director, actors, year):
        self.title = title
        self.runtime = runtime
        self.director = director
        self.actors = actors
        self.year = year


movies = [
    Movie(
        title="Magnolia",
        year=1999,
        runtime=188,
        director='Paul Thomas Anderson',
        actors=[
            'Tom Cruise',
            'Jason Robards',
            'Philip Seymour Hoffman',
            'Julianne Moore',
            'Philip Baker Hall',
            'John C. Reilly',
            'Alfred Molina',
            'William H. Macy',
        ]
    ),
    Movie(
        title='Once Upon a Time in the West',
        year=1968,
        runtime=165,
        director='Sergio Leone',
        actors=['Henry Fonda', 'Charles Bronson', 'Jason Robards'],
    ),
    Movie(
        title='Requiem for a Dream',
        year=2000,
        runtime=102,
        director='Darren Aronofsky',
        actors=['Jared Leto', 'Marlon Wayans', 'Ellen Burstyn'],
    ),
    Movie(
        title='True Romance',
        year=1993,
        runtime=119,
        director='Tony Scott',
        actors=['Christian Slater', 'Dennis Hopper', 'Val Kilmer', 'Patricia Arquette', 'Christopher Walken'],
    ),
    Movie(
        title='Oldboy',
        year=2003,
        runtime=120,
        director='Park Chan-wook',
        actors=['Choi Min-sik', 'Yoo Ji-tae', 'Kim Byeong-Ok'],
    ),
    Movie(
        title='Lady Vengeance',
        year=2005,
        runtime=115,
        director='Park Chan-wook',
        actors=['Jeong-nam Choi', 'Choi Min-sik'],
    ),
    Movie(
        title='The Handmaiden',
        year=2016,
        runtime=145,
        director='Park Chan-wook',
        actors=['Ha Jung-woo', 'Cho Jin-woong'],
    ),
    Movie(
        title='The Master',
        year=2012,
        runtime=138,
        director='Paul Thomas Anderson',
        actors=['Joaquin Phoenix', 'Philip Seymour Hoffman', 'Jesse Plemons', 'Amy Adams'],
    ),
    Movie(
        title='Phantom Thread',
        year=2017,
        runtime=130,
        director='Paul Thomas Anderson',
        actors=['Daniel Day-Lewis'],
    ),
    Movie(
        title='There Will Be Blood',
        year=2007,
        runtime=158,
        director='Paul Thomas Anderson',
        actors=['Daniel Day-Lewis', 'Paul Dano', 'Ciaran Hinds', 'Martin Stringer'],
    ),
    Movie(
        title='The Good, the Bad and the Ugly',
        year=1966,
        runtime=161,
        director='Sergio Leone',
        actors=['Clint Eastwood', 'Eli Wallach', 'Lee Van Cleef'],
    ),
    Movie(
        title='A Fistful of Dollars',
        year=1964,
        runtime=99,
        director='Sergio Leone',
        actors=['Clint Eastwood'],
    ),
    Movie(
        title='For a Few Dollars More',
        year=1965,
        runtime=132,
        director='Sergio Leone',
        actors=['Clint Eastwood', 'Lee Van Cleef'],
    ),
    Movie(
        title='Black Swan',
        year=2010,
        runtime=108,
        director='Darren Aronofsky',
        actors=['Vincent Cassel', 'Natalie Portman', 'Mila Kunis', 'Winona Ryder'],
    ),
    Movie(
        title='Blade Runner',
        year=1982,
        runtime=117,
        director='Ridley Scott',
        actors=['Harrison Ford', 'Rutger Hauer', 'Edward James Olmos'],
    ),
    Movie(
        title='Blade Runner 2049',
        year=2017,
        runtime=164,
        director='Denis Villeneuve',
        actors=['Harrison Ford', 'Ryan Gosling', 'Dave Bautista'],
    ),
    Movie(
        title="Miller's Crossing",
        year=1990,
        runtime=115,
        director='Coen Brothers',
        actors=['Gabriel Byrne', 'Albert Finney', 'John Turturro'],
    ),
   Movie(
        title='No Country for Old Men',
        year=2007,
        runtime=122,
        director='Coen Brothers',
        actors=['Tommy Lee Jones', 'Javier Bardem', 'Josh Brolin', 'Woody Harrelson'],
    ),
    Movie(
        title='True Grit',
        year=2010,
        runtime=110,
        director='Coen Brothers',
        actors=['Jeff Bridges', 'Matt Damon', 'Josh Brolin'],
    ),
    Movie(
        title='Fargo',
        year=1996,
        runtime=98,
        director='Coen Brothers',
        actors=['Steve Buscemi', 'Peter Stormare', 'William H. Macy', 'Frances McDormand'],
    ),
    Movie(
        title='The Big Lebowski',
        year=1998,
        runtime=117,
        director='Coen Brothers',
        actors=['Jeff Bridges', 'John Goodman', 'Steve Buscemi', 'Philip Seymour Hoffman', 'Julianna Moore'],
    ),
    Movie(
        title='The Martian',
        year=2015,
        runtime=144,
        director='Ridley Scott',
        actors=['Matt Damon', 'Sean Bean'],
    ),
    Movie(
        title='Stranger Than Fiction',
        year=2006,
        runtime=113,
        director='Marc Forster',
        actors=['Will Ferrell', 'Dustin Hoffman', 'Emma Thompson', 'Maggie Gyllenhaal'],
    ),
    Movie(
        title='Batman Begins',
        year=2005,
        runtime=140,
        director='Christopher Nolan',
        actors=['Christian Bale', 'Michael Caine', 'Ken Watanabe', 'Liam Neeson', 'Gary Oldman', 'Cillian Murphy'],
    ),
    Movie(
        title='The Dark Knight',
        year=2008,
        runtime=152,
        director='Christopher Nolan',
        actors=['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine', 'Gary Oldman', 'Cillian Murphy', 'Maggie Gyllenhaal'],
    ),
    Movie(
        title='The Dark Knight Rises',
        year=2012,
        runtime=164,
        director='Christopher Nolan',
        actors=['Christian Bale', 'Tom Hardy', 'Gary Oldman', 'Michael Caine', 'Cillian Murphy'],
    ),
    Movie(
        title='The Prestige',
        year=2006,
        runtime=130,
        director='Christopher Nolan',
        actors=['Christian Bale', 'Hugh Jackman', 'Michael Caine', 'Scarlett Johansson'],
    ),
    Movie(
        title='Inception',
        year=2010,
        runtime=148,
        director='Christopher Nolan',
        actors=['Tom Hardy', 'Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Ken Watanabe', 'Cillian Murphy'],
    ),
    Movie(
        title='Interstellar',
        year=2014,
        runtime=169,
        director='Christopher Nolan',
        actors=['Matthew McConaughey', 'Ellen Burstyn', 'Casey Affleck', 'Michael Caine', 'Anne Hathaway', 'Jessica Chastain'],
    ),
        Movie(
        title='Arrival',
        year=2016,
        runtime=116,
        director='Denis Villeneuve',
        actors=['Jeremy Renner', 'Forest Whitaker', 'Amy Adams'],
    ),
    Movie(
        title='Prisoners',
        year=2013,
        runtime=153,
        director='Denis Villeneuve',
        actors=['Hugh Jackman', 'Jake Gyllenhaal', 'Viola Davis', 'Melissa Leo'],
    ),
    Movie(
        title='In Bruges',
        year=2008,
        runtime=107,
        director='Martin McDonagh',
        actors=['Colin Farrell', 'Brendan Gleeson', 'Ciaran Hinds'],
    ),
    Movie(
        title='Seven Psychopaths',
        year=2012,
        runtime=110,
        director='Martin McDonagh',
        actors=['Colin Farrell', 'Woody Harrelson', 'Sam Rockwell', 'Christopher Walken'],
    ),
    Movie(
        title='Three Billboards Outside Ebbing, Missouri',
        year=2017,
        runtime=115,
        director='Martin McDonagh',
        actors=['Frances McDormand', 'Woody Harrelson', 'Sam Rockwell', 'Caleb Landry Jones'],
    ),
]